services:
  app_blue:
    image: "${BLUE_IMAGE}"
    container_name: app_blue
    restart: always
    environment:
      - PORT=${PORT}
      - RELEASE_ID=${RELEASE_ID_BLUE}
      - APP_POOL=blue
    ports:
      - "8081:${PORT}"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:${PORT}/healthz || exit 1"]
      interval: 2s
      timeout: 2s
      retries: 2

  app_green:
    image: "${GREEN_IMAGE}"
    container_name: app_green
    restart: always
    environment:
      - PORT=${PORT}
      - RELEASE_ID=${RELEASE_ID_GREEN}
      - APP_POOL=green
    ports:
      - "8082:${PORT}"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:${PORT}/healthz || exit 1"]
      interval: 2s
      timeout: 2s
      retries: 2

  nginx:
    image: "nginx:stable-alpine"
    container_name: nginx_bluegreen
    depends_on:
      - app_blue
      - app_green
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template:ro
      - ./nginx/docker-entrypoint.sh:/docker-entrypoint.sh:ro
      - /var/log/nginx:/var/log/nginx
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL}
      - PRIMARY_NAME=
      - BACKUP_NAME=
    entrypoint: ["/bin/sh","/docker-entrypoint.sh"]
    restart: always

  log_tailer:
    image: alpine:latest
    container_name: log_tailer
    depends_on:
      - nginx
    volumes:
      - nginx-logs:/var/log/nginx
    command: sh -c "tail -f /var/log/nginx/access.json.log"

  alert_watcher:
    build:
     context: ./alert_watcher
    container_name: alert_watcher
    depends_on:
      - nginx
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL}
      - NGINX_CONTAINER=nginx_bluegreen
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - ERROR_THRESHOLD=${ERROR_THRESHOLD:-5}
      - ALERT_COOLDOWN=${ALERT_COOLDOWN:-60}
      - MAINTENANCE_MODE=${MAINTENANCE_MODE:-false}
    volumes:
      - /var/log/nginx:/var/log/nginx
    restart: always
